### ISSUE TITLE
java.lang.RuntimeException: OGR Error: General Error

### ISSUE THREAD

**Issue by RGregat** [paamand/GDAL#10]
I compiled the AAR file as shown in the README. To test everything i wanted to transform a coordinate 
```
Driver memDriver = gdal.GetDriverByName("MEM");
Dataset ds1 = memDriver.Create("mem", 100, 100);
ds1.SetGeoTransform(new double[]{2, 0.01, 0, 49, 0, -0.01});
SpatialReference sr1 = new SpatialReference();
sr1.ImportFromEPSG(4326);
```
But the line `sr1.ImportFromEPSG(4326)`  throws an exception:

```
2019-04-25 10:45:47.274 3506-3506/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.gdaltest, PID: 3506
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.gdaltest/com.example.gdaltest.MainActivity}: java.lang.RuntimeException: OGR Error: General Error
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.RuntimeException: OGR Error: General Error
        at org.gdal.osr.osrJNI.SpatialReference_ImportFromEPSG(Native Method)
        at org.gdal.osr.SpatialReference.ImportFromEPSG(SpatialReference.java:569)
        at com.example.gdaltest.MainActivity.gdalTransform(MainActivity.java:54)
        at com.example.gdaltest.MainActivity.onCreate(MainActivity.java:30)
        at android.app.Activity.performCreate(Activity.java:7144)
        at android.app.Activity.performCreate(Activity.java:7135)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6718) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

Do I have to import more into my Android-Project?

**Comment by RGregat** [comment]
Ok it works if I insert the proj4 String directly

```
SpatialReference src = new SpatialReference();
SpatialReference dst = new SpatialReference();

src.ImportFromProj4("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs");
dst.ImportFromProj4("+proj=utm +zone=33 +ellps=WGS84 +datum=WGS84 +units=m +no_defs");

CoordinateTransformation tr = new CoordinateTransformation(src, dst);

double[] transformedPoint = tr.TransformPoint(13.3924355,52.5266776,0.0);
```

I guess that the epsg-list is missing?

**Comment by Canivek** [comment]
Yes you are missing a file to be able to call `SpatialReference.ImportFromEPSG(code)`

> This method will initialize the spatial reference based on the passed in EPSG GCS or PCS code. The coordinate system definitions are normally read from the EPSG derived support files such as pcs.csv, gcs.csv, pcs.override.csv, gcs.override.csv and falling back to search for a PROJ.4 epsg init file or a definition in epsg.wkt. 

See https://gdal.org/java/org/gdal/osr/SpatialReference.html#ImportFromEPSG-int- for more information.

**Comment by paamand** [comment]
We could maybe include the files in `/build/[abi]/share/gdal`?
I don't know how to properly package them into the aar so that gdal will find them, but maybe worth an effort?

**Comment by RGregat** [comment]
I would welcome this, if it is possible. Currently, I have no experience with the packaging of a AAR file. I had never the need to do it honestly, but I find it interesting and would take a look into this problem.

**Comment by RGregat** [comment]
I found now for myself a solution. I just package the missing **data** folder into my App. 
For this I put the data folder into the assets folder and copy it into the internal storage of my App. After that I set the GDAL_DATA config to point to the internal path.

```
public File copyGDALDataFolder() throws IOException {
        AssetManager assetManager = this.getAssets();

        String[] dataFileList = assetManager.list("data");

        File internalRootDataDir = new File(this.getFilesDir(), "data");

        if(!internalRootDataDir.exists()) {
            internalRootDataDir.mkdirs();
        }

        for(String assetFilePath : dataFileList) {
            Log.d(TAG, assetFilePath);

            File filePath = new File(internalRootDataDir, assetFilePath);

            if(!filePath.exists()) {

                InputStream inputStream = assetManager.open("data/" + assetFilePath);
                OutputStream outputStream = new FileOutputStream(new File(internalRootDataDir, assetFilePath));

                byte buffer[] = new byte[1024];
                int length = 0;

                while ((length = inputStream.read(buffer)) > 0) {
                    outputStream.write(buffer, 0, length);
                }

                outputStream.close();
                inputStream.close();
            }
        }

        return internalRootDataDir;
    }
```

```
if(internalRootDir != null) {
            File logFile = new File(this.getFilesDir(), "gdal.log");
            gdal.SetConfigOption("GDAL_DATA", internalRootDir.getAbsolutePath());
            gdal.SetConfigOption("CPL_LOG", logFile.getAbsolutePath());
            gdal.SetConfigOption("CPL_DEBUG", "ON");
            gdal.SetConfigOption("CPL_LOG_ERRORS", "ON");
            gdal.SetConfigOption("CPL_TIMESTAMP ", "ON");
        }
```

```
gdal.AllRegister();
```
